### ISSUE TITLE
Need documentation or usage examples

### ISSUE THREAD

**Issue by pr0xr** [cpuguy83/dockerhub-webhook-listener#1]
It would be great to see some documentation or examples on how to use it. I have read the blogpost on http://blog.docker.com/2014/08/automagical-deploys-from-docker-hub/ but i still have some issues. Ive tested different urls to communicate with the listener but i seem to have issues with the TLS.

Here is the output when using TLS and testing the hooks from the hub:

```
56ee423aa76c hub-listener → ./hub-listener -config-file=./config.ini -listen=0.0.0.0:80
2014/08/22 15:20:36 Starting server on 0.0.0.0:80
2014/08/22 15:20:36 Starting with SSL
2014/08/22 15:20:46 http: TLS handshake error from 54.237.235.85:39495: tls: unsupported SSLv2 handshake received
2014/08/22 15:20:58 http: TLS handshake error from 184.72.91.239:41831: tls: unsupported SSLv2 handshake received
2014/08/22 15:21:03 http: TLS handshake error from 184.72.91.239:42122: tls: unsupported SSLv2 handshake received
2014/08/22 15:21:26 http: TLS handshake error from 54.237.235.85:40923: tls: unsupported SSLv2 handshake received
2014/08/22 15:22:01 http: TLS handshake error from 162.242.195.71:53256: remote error: unknown certificate authority
```

**Comment by cpuguy83** [comment]
Did you tell the remote system to use https?
This looks like it might be the server expecting SSL but it got a non-SSL request.

**Comment by pr0xr** [comment]
The only components i used in the test was the urls from the hub and the listener. No server in the middle that passed the urls internally to the listener. I generated both cert and key with the script from the blogpost and generate_cert.go

**Comment by cpuguy83** [comment]
@pandrew Help me help you.
You need to make sure you told DockerHub to connect using https, otherwise the webhook listener is not going to know what to do with the request.

If the server is expecting an SSL handshake and the requesting client (dockerhub) is not sending one, then it's going to throw an error.

So, please make sure you have dockerhub connecting over https (not http) when setting this up.
