### ISSUE TITLE
DockerHub Webhook trigger Jenkins build

### ISSUE THREAD

**Issue by sunshineo** [cpuguy83/dockerhub-webhook-listener#2]
I tried to use https://github.com/jenkinsci/dockerhub-plugin but failed. This project seems to be exactly what I want, but it seems that this project is not being actively developed. The documentation is basically 0. Is there any plan to move forward with this project? Is there any other project that can do same/similar things?

My project currently fails to pull the docker image from DockerHub. I need to install docker on the Jenkins host, right? And also my image on DockerHub is private. How can I pull the image?

So when configure the Jenkins project, I need to enter the "Image ID" for the image that it will pull from DockerHub. However the whole point is that I want Jenkins to do some testing and then tell DockerHub it passed or not and then DockerHub can publish the image or not. So is it possible to use the content of the WebHook that DockerHub sent to Jenkins to pull the image (which I believe is not published yet)?

Thank you very much!

--Gordon

**Comment by cpuguy83** [comment]
It's not actively developed because it is, for all intents and purposes, done... at least until DockerHub changes stuff around.

re: documentation, please see the example mailgun and logging handlers for writing your own.
If you'd like to submit some better docs, then I'd be happy to review and merge PR.

Thanks.

**Comment by sunshineo** [comment]
Thank you @cpuguy83 I don't think I posted the question on the right place or I did not articulated clearly. I was talking about a different but related project. The other project implemented docker hub webhook inside Jenkins. But kinda broken. I wonder if anyone used your project to work with Jenkins. Thanks!

**Comment by cpuguy83** [comment]
I have used it before, and I know of a few other projects that do... it's been awhile since I've touched it, though.

**Comment by sunshineo** [comment]
What other projects? Can you point me to some?

**Comment by cpuguy83** [comment]
Private stuff we've used for demos, so not really.

**Comment by sunshineo** [comment]
Thank you anyway!
